window.APP_CONFIG = {
  name: "Footage Archive",
  signature: "Registros Fantasmas",
  logoImage: "https://xcjzydmprmbpbqkacjwb.supabase.co/storage/v1/object/public/avatars/avatar-1783883751088.png",
  logoAlt: "Footage Archive",
  accessPin: "0906",
  intro: "Un pequeño archivo de todo lo que siento.",
  lastUpdated: "2026-09-03",
  visual: {
    letterMinHeight: "1400px",
    letterContentMinHeight: "900px"
  },
  texts: {
    system: {
      randomMessages: ["Hay cosas bonitas que solo aparecen cuando vuelves.", "Este archivo guarda más de lo que parece.", "Una pausa también puede ser un recuerdo.", "Quédate un momento, aquí todo habla de ti.", "Algunas historias merecen una segunda mirada.", "Lo mejor de este lugar aparece sin avisar.", "Guarda este instante cerca del corazón.", "Hay recuerdos que saben esperar.", "Tu historia también merece un lugar bonito.", "Vuelve despacio, aquí nada tiene prisa.", "A veces una imagen dice todo.", "Este pequeño archivo sigue creciendo contigo.", "La memoria tiene su propia luz.", "Quédate con lo que te haga sonreír.", "Hay días que merecen repetirse.", "Todo lo importante cabe en un instante.", "Un detalle puede cambiar todo el día.", "Aquí viven las cosas que no queremos perder.", "La distancia no borra lo que importa.", "El tiempo también sabe cuidar.", "Una pausa, una mirada, un recuerdo.", "Lo sencillo suele quedarse más tiempo.", "Hay lugares que se sienten como casa.", "Este mensaje llegó justo cuando debía.", "Cada visita encuentra algo distinto.", "Lo bonito también puede ser cotidiano.", "Las historias más sinceras hablan bajito.", "Este rincón guarda una parte de ti.", "Que nunca falten motivos para volver.", "Algunas emociones prefieren quedarse escritas."],
      hearts: ["♥", "♡", "❤", "♥︎", "♡"],
      accessTitles: ["Una pequeña<br><em>clave.</em>", "Un instante<br><em>privado.</em>", "Un recuerdo<br><em>para ti.</em>", "Antes de entrar,<br><em>respira.</em>", "Una puerta<br><em>secreta.</em>", "Algo bonito<br><em>te espera.</em>", "Un rincón<br><em>de nosotros.</em>", "La memoria<br><em>continúa.</em>"],
      morning: "Buenos días",
      afternoon: "Buenas tardes",
      evening: "Buenas noches",
      updateNote: "Se actualiza entre días ·",
      interactive: "Elemento interactivo",
      hiddenImageAlt: "Imagen escondida del archivo",
      previous: "Anterior",
      next: "Siguiente",
      imageChange: "Cambiar imagen",
      closeSecret: "Cerrar secreto",
      secretEyebrow: "DESCUBRIMIENTO ·",
      secretTitle: "Has encontrado<br><em>algo nuestro.</em>",
      secretHint: "Pista: vuelve a mirar los pequeños detalles del archivo.",
      hiddenSong: "Abrir la canción escondida",
      hiddenSongTitle: "Canción escondida",
      offlineNote: "Sin conexión. No se enviarán mensajes hasta recuperar Internet.",
      offlineGallery: "Sin conexión · imagen no sincronizada",
      onlineNote: "Conexión recuperada · ya puedes enviar.",
      onlineGallery: "Conexión recuperada · galería lista",
      pendingSupabase: "Supabase pendiente · configura url y anonKey",
      pendingSupabaseNote: "Supabase está pendiente: configura la URL y anonKey antes de enviar.",
      connected: "Conexión lista · tus mensajes se guardarán en Supabase.",
      galleryError: "Supabase · revisa galleryTable y sus permisos",
      clientError: "No se pudo cargar el cliente de Supabase",
      imageTypeError: "Selecciona un archivo de imagen válido.",
      unavailable: "No se puede sincronizar: Supabase o la conexión no están disponibles. No se ha guardado la imagen.",
      syncing: "Sincronizando imagen del muro",
      synced: "sincronizado",
      imageSyncError: "No se pudo sincronizar la imagen. No se ha guardado nada. Revisa Storage, tabla y permisos.",
      emptyMessage: "No se puede enviar un mensaje vacío. Escribe algo antes de continuar.",
      sending: "Enviando mensaje...",
      sent: "Mensaje enviado correctamente.",
      sendUnavailable: "No se puede enviar: Supabase o la conexión no están disponibles. No se ha enviado nada.",
      sendError: "No se pudo enviar: la tabla de comentarios o la API tienen un error. No se ha guardado nada.",
      wrongPin: "Ese no es el código todavía.",
      sectionAccessTitle: "Antes de continuar,<br><em>una clave.</em>",
      sectionAccessCopy: "Cada sección guarda una pequeña sorpresa.",
      secretAccessTitle: "Encontraste<br><em>un secreto.</em>",
      secretAccessCopy: "La clave también abre lo que está escondido.",
      loadingFallback: "FA"
    },
    elements: {
      "title": "Footage Archive",
      ".loader p": "abriendo footage archive",
      ".access-box > .eyebrow": "FOOTAGE ARCHIVE · ACCESO PRIVADO",
      "#access-title": "Una pequeña<br><em>clave.</em>",
      "#access-copy": "Escribe el PIN para entrar a este recuerdo.",
      "#pin-form button": "Abrir archivo <span>↗</span>",
      ".guide-button": "Guía <span>?</span>",
      ".sound-button": "Instalar <span>↗</span>",
      ".hero .eyebrow": "ARCHIVO PRIVADO · 2025 — 2026",
      "#hero-title": "Footage<br><em>Archive.</em>",
      ".art-label": "vol. 01<br><span>de nosotros</span>",
      ".menu-links a:nth-child(1) span:nth-child(2)": "Cartas",
      ".menu-links a:nth-child(2) span:nth-child(2)": "Galería",
      ".menu-links a:nth-child(3) span:nth-child(2)": "Notas",
      ".site-footer span:first-child": "© Registros Fantasmas",
      ".site-footer span:last-child": "Todos los derechos reservados",
      ".letters-section .eyebrow": "02 / CORRESPONDENCIA",
      ".letters-section h1": "Cartas para<br><em>quedarnos.</em>",
      ".letters-section .section-note": "Palabras para leer despacio,<br>cuando quieras volver.",
      ".letters-section .spotify-wrap .eyebrow": "BANDA SONORA",
      ".letters-section .spotify-wrap h3": "La canción que<br>suena a nosotros.",
      ".gallery-section .eyebrow": "03 / GALERÍA DIGITAL",
      ".gallery-section h1": "Muros que<br><em>se mueven.</em>",
      ".notes-section .eyebrow": "04 / DEJA UNA NOTA",
      ".notes-section h1": "Tu voz también<br><em>vive aquí.</em>",
      ".note-form label:first-of-type": "Tu nombre",
      ".note-form label:nth-of-type(2)": "Tu mensaje",
      ".note-form button[type=submit]": "Guardar nota <span>↗</span>",
      ".full-letter .primary-link": "Volver a las cartas <span>↙</span>"
    },
    browserTitle: "Footage Archive",
    loader: "abriendo footage archive",
    accessEyebrow: "FOOTAGE ARCHIVE · ACCESO PRIVADO",
    accessCopy: "Escribe el PIN para entrar a este recuerdo.",
    accessButton: "Abrir archivo",
    pinLabel: "Introduce tu PIN",
    pinPlaceholder: "0 0 0 0",
    navigation: { home: "Inicio", letters: "Cartas", gallery: "Galería", notes: "Notas" },
    home: {
      eyebrow: "ARCHIVO PRIVADO · 2025 — 2026",
      heroTitle: "Footage<br><em>Archive.</em>",
      artLabel: "vol. 01<br><span>de nosotros</span>",
      footer: "Todos los derechos reservados"
    },
    letters: {
      eyebrow: "02 / CORRESPONDENCIA",
      title: "Cartas para<br><em>quedarnos.</em>",
      note: "Palabras para leer despacio,<br>cuando quieras volver.",
      soundtrack: "BANDA SONORA",
      soundtrackTitle: "La canción que<br>suena a nosotros.",
      open: "Abrir archivo ↗",
      fallbackDetail: "Una carta guardada para ti.",
      pageTitle: "Cartas · Footage Archive"
    },
    gallery: {
      eyebrow: "03 / GALERÍA DIGITAL",
      title: "Muros que<br><em>se mueven.</em>",
      previous: "Muro anterior",
      next: "Muro siguiente",
      change: "presiona para cambiar",
      pageTitle: "Galería · Footage Archive"
    },
    notes: {
      eyebrow: "04 / DEJA UNA NOTA",
      title: "Tu voz también<br><em>vive aquí.</em>",
      nameLabel: "Tu nombre",
      namePlaceholder: "¿Cómo te llamas?",
      messageLabel: "Tu mensaje",
      messagePlaceholder: "Escribe algo bonito para que quede guardado.",
      submit: "Guardar nota",
      greetingName: "Nohelia",
      loveTitle: "El Amor de<br><em>Mi Vida.</em>",
      pageTitle: "Notas · Footage Archive"
    },
    letter: {
      open: "Abrir carta",
      close: "Cerrar carta",
      flowerLabel: "Tocar la flor",
      soundtrack: "BANDA SONORA DE ESTA CARTA",
      signature: "Con cariño, para leerlo despacio.",
      back: "Volver a las cartas"
    },
    footer: "© Registros Fantasmas"
  },
  spotifyEmbed: "https://open.spotify.com/embed/track/11dFghVXANMlKmJXsNCbNl?utm_source=generator&theme=0",
  supabase: {
    url: "https://xcjzydmprmbpbqkacjwb.supabase.co",
    anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhjanp5ZG1wcm1icGJxa2FjandiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwNzY1NjEsImV4cCI6MjA4MzY1MjU2MX0.Bpr4H2iZPl5JWW8rTXp4nBiB1Z_c7pIhKXiThydeNUw",
    galleryTable: "gallery_items",
    commentsTable: "comentarios",
    commentsMessageColumn: "mensaje",
    galleryBucket: "gallery"
  },
  letters: [
    { year: "2025", date: "Octubre", title: "Para cuando necesites recordar", text: "Han pasado cuatro meses desde que comenzamos este vuelo juntos, y en todo este tiempo hemos vivido de todo: risas que se quedan grabadas en la memoria, silencios que a veces pesaban, discusiones que nos enseñaron a entendernos mejor, momentos de distancia que nunca rompieron lo que sentimos, y lágrimas compartidas que me hicieron ver tu vulnerabilidad y fuerza al mismo tiempo. Me has confiado cosas profundas de ti, me has permitido entrar en tu mundo y yo he intentado estar ahí para ti en cada instante, siendo tu apoyo, tu refugio y tu compañero. Siempre he sentido que somos el complemento perfecto, que nos equilibramos en nuestros defectos y nos potenciamos en nuestras virtudes. Incluso cuando algo duele o nos pone a prueba, seguimos avanzando juntos porque tú haces tu mejor esfuerzo siempre, porque me das tu soporte constante, porque hemos aprendido a comunicar lo que sentimos aunque es complejo. Todo eso, Nohelia, todo lo que somos y lo que hemos construido, me hace sentir que no hay otra persona con quien quisiera compartir este viaje. Cada momento, cada detalle, cada mirada y gesto de ternura que me das me hace admirarte y querer seguir construyendo esto contigo día tras día. Cada piloto necesita a su pareja de ala, y eso eres tú. Por eso hoy, al cumplir cuatro meses, quiero que sepas que cada instante, incluso los difíciles, ha valido la pena porque me ha acercado más a ti.", detail: "Un comienzo que merece quedarse guardado.", page: "carta-01.html", spotifyEmbed: "https://open.spotify.com/embed/track/5Hg1m5uhSPL75ejQgPOmyc?utm_source=generator&theme=0" },
    { year: "2026", date: "Enero", title: "Lo que no digo suficiente", text: "Escribe aquí el contenido completo de tu segunda carta. Deja aquí ese mensaje que merece quedarse guardado.", detail: "Todo lo que a veces cuesta decir en voz alta.", page: "carta-02.html", spotifyEmbed: "https://open.spotify.com/embed/track/11dFghVXANMlKmJXsNCbNl?utm_source=generator&theme=0" },
    { year: "2026", date: "Febrero", title: "Hoy también te elijo", text: "Escribe aquí el contenido completo de tu carta actual. Este espacio es completamente tuyo y de tus palabras.", detail: "Una elección que vuelve a suceder cada día.", page: "carta-03.html", spotifyEmbed: "https://open.spotify.com/embed/track/11dFghVXANMlKmJXsNCbNl?utm_source=generator&theme=0" },
    { year: "2026", date: "Marzo", title: "La calma de encontrarte", text: "Hay personas que llegan y hacen que el ruido del mundo baje un poco. Esta carta guarda esa calma.", detail: "Para los días que necesitan un refugio.", page: "carta-04.html", spotifyEmbed: "https://open.spotify.com/embed/track/11dFghVXANMlKmJXsNCbNl?utm_source=generator&theme=0" },
    { year: "2026", date: "Abril", title: "Lo que construimos", text: "Cada pequeño gesto ha ido formando una historia que se parece a nosotros. Aquí queda una parte de ese camino.", detail: "Un mapa hecho de instantes compartidos.", page: "carta-05.html", spotifyEmbed: "https://open.spotify.com/embed/track/11dFghVXANMlKmJXsNCbNl?utm_source=generator&theme=0" },
    { year: "2026", date: "Mayo", title: "Para leer despacio", text: "No hace falta tener todas las respuestas. A veces basta con quedarse, mirar y recordar lo que sí sabemos.", detail: "Una pausa para volver al centro.", page: "carta-06.html", spotifyEmbed: "https://open.spotify.com/embed/track/11dFghVXANMlKmJXsNCbNl?utm_source=generator&theme=0" },
    { year: "2026", date: "Julio", title: "Tu forma de iluminar", text: "Hay una luz tuya que aparece en las cosas más sencillas: una palabra, una risa, una mirada que llega a tiempo.", detail: "Para guardar la luz de lo cotidiano.", page: "carta-07.html", spotifyEmbed: "https://open.spotify.com/embed/track/11dFghVXANMlKmJXsNCbNl?utm_source=generator&theme=0" },
    { year: "2026", date: "Junio", title: "Todavía nos quedan días", text: "El futuro no tiene que ser perfecto para ser bonito. Me basta saber que todavía nos quedan muchos días por llenar.", detail: "Una promesa abierta hacia adelante.", page: "carta-08.html", spotifyEmbed: "https://open.spotify.com/embed/track/11dFghVXANMlKmJXsNCbNl?utm_source=generator&theme=0" },
    { year: "2026", date: "Agosto", title: "Donde siempre vuelvo", text: "Entre todos los lugares del mundo, hay uno que reconozco sin mirar: el lugar donde estás tú.", detail: "Un hogar que no necesita paredes.", page: "carta-09.html", spotifyEmbed: "https://open.spotify.com/embed/track/11dFghVXANMlKmJXsNCbNl?utm_source=generator&theme=0" },
    { year: "2026", date: "Septiembre", title: "Lo que el tiempo confirma", text: "El tiempo no se ha llevado lo importante. Al contrario: ha dejado más claro todo aquello que vale la pena cuidar.", detail: "Para celebrar lo que permanece.", page: "carta-10.html", spotifyEmbed: "https://open.spotify.com/embed/track/11dFghVXANMlKmJXsNCbNl?utm_source=generator&theme=0" },
    { year: "2026", date: "Noviembre", title: "Una vida de pequeños momentos", text: "Quizá la felicidad no sea un momento enorme, sino esta colección de instantes pequeños que seguimos eligiendo.", detail: "La belleza de lo que sucede cada día.", page: "carta-11.html", spotifyEmbed: "https://open.spotify.com/embed/track/11dFghVXANMlKmJXsNCbNl?utm_source=generator&theme=0" }
  ],
  secrets: [
    ...["una canción", "una mirada", "una tarde", "un abrazo", "una promesa", "una fotografía", "una risa", "un mensaje", "un paseo", "un deseo"].flatMap((clue, index) => [
      `Secreto ${index * 10 + 1}: guarda ${clue} como si fuera un pequeño tesoro.`,
      `Secreto ${index * 10 + 2}: hay algo especial en ${clue} cuando lo compartes con ella.`,
      `Secreto ${index * 10 + 3}: la pista estaba escondida en ${clue}.`,
      `Secreto ${index * 10 + 4}: vuelve a ${clue} y mira lo que antes no viste.`,
      `Secreto ${index * 10 + 5}: ${clue} también puede ser una forma de decir te quiero.`,
      `Secreto ${index * 10 + 6}: este instante nació alrededor de ${clue}.`,
      `Secreto ${index * 10 + 7}: alguien pensó en ti mientras aparecía ${clue}.`,
      `Secreto ${index * 10 + 8}: la mejor parte de ${clue} todavía está por descubrirse.`,
      `Secreto ${index * 10 + 9}: si encuentras ${clue}, encontrarás una sonrisa.`,
      `Secreto ${index * 10 + 10}: nunca subestimes el poder de ${clue}.`
    ])
  ],
  galleryFallback: [
    { title: "Muro 01", caption: "Un instante que se quedó", image: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 02", caption: "La luz de aquel día", image: "https://images.unsplash.com/photo-1494774157365-9e04c6720e47?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 03", caption: "Donde todo se siente cerca", image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 04", caption: "Una tarde para guardar", image: "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 05", caption: "Pequeñas cosas que brillan", image: "https://images.unsplash.com/photo-1490730141103-6cac27abb37f?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 06", caption: "El mundo después de la lluvia", image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 07", caption: "Un lugar al que volver", image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 08", caption: "La calma de estar juntos", image: "https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 09", caption: "Colores de un recuerdo", image: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 10", caption: "La hora dorada", image: "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 11", caption: "Respirar despacio", image: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 12", caption: "Una ventana abierta", image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 13", caption: "Cerca del mar", image: "https://images.unsplash.com/photo-1507525425161-6c3a1d5b1c4a?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 14", caption: "La belleza de lo cotidiano", image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 15", caption: "Un paseo sin prisa", image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 16", caption: "Todo lo que queda en la luz", image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85&sat=-10" },
    { title: "Muro 17", caption: "El cielo nos acompaña", image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 18", caption: "Silencio bonito", image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85&hue=20" },
    { title: "Muro 19", caption: "Una historia en cada esquina", image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 20", caption: "Cuando el día se vuelve suave", image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85&blur=1" },
    { title: "Muro 21", caption: "Instantes de domingo", image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 22", caption: "La música de la tarde", image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 23", caption: "Un recuerdo en movimiento", image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 24", caption: "La ciudad también abraza", image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 25", caption: "Donde empieza la aventura", image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 26", caption: "Una pausa entre flores", image: "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 27", caption: "El color de los días felices", image: "https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 28", caption: "Lugares que dicen tu nombre", image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 29", caption: "La noche guarda secretos", image: "https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 30", caption: "Una mirada hacia arriba", image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85&fm=jpg" },
    { title: "Muro 31", caption: "Lo que florece sin avisar", image: "https://images.unsplash.com/photo-1455587734955-081b22074882?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 32", caption: "Un rincón de paz", image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 33", caption: "La luz entre las hojas", image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 34", caption: "Días que se quedan", image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=85&fit=crop" },
    { title: "Muro 35", caption: "Un pedacito de cielo", image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 36", caption: "La ternura de lo sencillo", image: "https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&w=1200&q=85&ixlib=rb-4.1.0" },
    { title: "Muro 37", caption: "Una memoria luminosa", image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 38", caption: "Hasta el último detalle", image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=85&sat=5" },
    { title: "Muro 39", caption: "Aquí también hay hogar", image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=85" },
    { title: "Muro 40", caption: "Para volver cuando quieras", image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=85" }
  ]
};
